update @clz and function callbacks for 0.10; make linenoiseX functions
joachimschmidt557/linenoize pull request #6
Opened 2022-11-11 18:33 UTC by garrisonhh

It looks like linenoize doesn't compile with the current zig version, so I fixed some compilation errors.

I also made some functions public that seem like they should be, unsure if this is the intention of them originally

2022-11-12 20:57 UTC, notramo requested changes
Some modifications are required for making it compile on stage 1 also.
Unfortunately, runtime performance of stage 2 is 10< times worse in some cases (https://github.com/ziglang/zig/issues/12518), so it's necessary to use stage 1 in some projects, until stage 2 can produce the same runtime performance.

2022-11-12 20:57 UTC, notramo commented on src/main.zig
> +pub const CompletionsCallback = *fn (Allocator, []const u8) Allocator.Error![]const []const u8;
The stage1 compiler requires the callbacks to be functions, not a function pointers.
These are referenced in line 152 and 227 in the `fun` variable. Currently, it is called like this:
```zig
try fun(self.allocator, self.buf.items);
```
Stage 1 can not dereference automatically, so a slight modification is required:
```zig
try fun.*(self.allocator, self.buf.items);
```
To support conditional compilation, depending on the compiler backend, it should be called like this:
```zig
const builtin = @import("builtin");
try (if (builtin.zig_backend == .stage1) fun.* else fun)(self.allocator, self.buf.items);
```

2022-11-12 22:12 UTC, garrisonhh commented
I switched them to `std.meta.FnPtr` instead, and also fixed the analagous decls I found in `c.zig`!

2022-11-12 22:13 UTC, garrisonhh commented
thanks for the catch :)

2022-11-13 21:24 UTC, joachimschmidt557 reviewed
Thanks a lot for your contribution! Just one thing - it is intentional that only the `Linenoise.linenoise` function is the public API (similar to the original linenoise).

2022-11-13 21:24 UTC, joachimschmidt557 commented on src/main.zig
> +pub fn linenoiseEdit(ln: *Linenoise, in: File, out: File, prompt: []const u8) !?[]const u8 {
These functions are intentionally not public as the API surface is intended to have only one entry point (`Linenoise.linenoise`).

2022-11-17 10:08 UTC, joachimschmidt557 approved these changes

2022-11-17 10:09 UTC, merged

2022-11-17 10:09 UTC, joachimschmidt557 commented
Thanks!